//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aldentea.SweetMutus.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aldentea.SweetMutus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Edit(_E) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuEdit {
            get {
                return ResourceManager.GetString("MenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Redo(_R) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuEditRedo {
            get {
                return ResourceManager.GetString("MenuEditRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Undo(_U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuEditUndo {
            get {
                return ResourceManager.GetString("MenuEditUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(_F) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFile {
            get {
                return ResourceManager.GetString("MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(_X) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileExit {
            get {
                return ResourceManager.GetString("MenuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export(_E)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileExport {
            get {
                return ResourceManager.GetString("MenuFileExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New(_N) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileNew {
            get {
                return ResourceManager.GetString("MenuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(_O)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileOpen {
            get {
                return ResourceManager.GetString("MenuFileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open from history(_H) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileOpenFromHistory {
            get {
                return ResourceManager.GetString("MenuFileOpenFromHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(_S) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileSave {
            get {
                return ResourceManager.GetString("MenuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as(_A)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileSaveAs {
            get {
                return ResourceManager.GetString("MenuFileSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save for HyperMutus(_M)... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuFileSaveForHyperMutus {
            get {
                return ResourceManager.GetString("MenuFileSaveForHyperMutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   View(_V) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Categories(_C) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewCategories {
            get {
                return ResourceManager.GetString("MenuViewCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FileName Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewFileNameColumn {
            get {
                return ResourceManager.GetString("MenuViewFileNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ID Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewIDColumn {
            get {
                return ResourceManager.GetString("MenuViewIDColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memo Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewMemoColumn {
            get {
                return ResourceManager.GetString("MenuViewMemoColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Player Control Buttons に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewPlayerControlButtons {
            get {
                return ResourceManager.GetString("MenuViewPlayerControlButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play Position Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewPlayPositionColumn {
            get {
                return ResourceManager.GetString("MenuViewPlayPositionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Seek Position Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewSeekPositionColumn {
            get {
                return ResourceManager.GetString("MenuViewSeekPositionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Position Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MenuViewStopPositionColumn {
            get {
                return ResourceManager.GetString("MenuViewStopPositionColumn", resourceCulture);
            }
        }
    }
}
